#!/usr/bin/env bash
#display bad luck at 4th line, good luck at 8th and holberton school for the rest.
count=1
while [ $count -lt 10 ];
do
	if [ $count -eq 4 ];
	then
		echo bad luck
	elif [ $count -eq 8 ];
	then
		echo good luck
	else
		echo Holberton School
	fi
	let count++
done
