#!/usr/bin/env bash
#display bad luck at 4th line, good luck at 8th and holberton school for the rest.
count=1
while [ $count -le 20 ];
do
	echo $count
	case $count in
	4)
		echo bad luck from China
		;;
	9)
		echo bad luck from Japan
		;;
	17)
		echo bad luck from Italy
		;;
	*)
	esac
	let count++
done
